INSERT INTO PROFILE (ID, NAME, EMAIL, PASSWORD) VALUES (2423, 'Priyanshu', 'p@p.com', 'Kanpur');
INSERT INTO PROFILE (ID, NAME, EMAIL, PASSWORD) VALUES (9238, 'Himanshu', 'h@h.com', 'Jaipur');
INSERT INTO PROFILE (ID, NAME, EMAIL, PASSWORD) VALUES (9932, 'Mark Jain', 'm@m.com', 'Bharatpur');
INSERT INTO PROFILE (ID, NAME, EMAIL, PASSWORD) VALUES (4348, 'Saurabh', 's@s.com', 'Dehradun');
INSERT INTO PROFILE (ID, NAME, EMAIL, PASSWORD) VALUES (1239, 'Rishabh', 'r@r.com', 'Meghalaya');
INSERT INTO PROFILE (ID, NAME, EMAIL, PASSWORD) VALUES (7432, 'Ravishankar', 'ra@ra.com', 'Manipur');

INSERT INTO POST (POST_ID, POST_CONTENT, POST_DATE, POST_COMMENT) VALUES (7432, 'Ravishankar', '2000-12-12', 'Manipur');
INSERT INTO POST (POST_ID, POST_CONTENT, POST_DATE, POST_COMMENT) VALUES (7321, 'Mathematics', '2001-1-1', 'KBC');
INSERT INTO POST (POST_ID, POST_CONTENT, POST_DATE, POST_COMMENT) VALUES (9232, 'Science', '2005-4-5', 'LMNOP');
INSERT INTO POST (POST_ID, POST_CONTENT, POST_DATE, POST_COMMENT) VALUES (2345, 'History', '2004-2-4', 'KYC');
INSERT INTO POST (POST_ID, POST_CONTENT, POST_DATE, POST_COMMENT) VALUES (1643, 'Computer Science', '2009-3-6','ABC');

INSERT INTO GROUPS (GROUP_ID, GROUP_SIZE) VALUES(2, 34);
INSERT INTO GROUPS (GROUP_ID, GROUP_SIZE) VALUES(1, 31);
INSERT INTO GROUPS (GROUP_ID, GROUP_SIZE) VALUES(5, 35);
INSERT INTO GROUPS (GROUP_ID, GROUP_SIZE) VALUES(3, 38);
INSERT INTO GROUPS (GROUP_ID, GROUP_SIZE) VALUES(6, 32);